Happy New Year !!

On the occasion of New year lets pratices Data Analysis from the begining to end.

#Codeing Life #KodetoDensiny

Here i am pratices Data Analysis from the begining you using a dataset

Here we are using the Dataset of salses - Superstore Dataset

In [1]:
# Libraries
import pandas as pd
import numpy as np

#### 1. Viewing & Understanding Data

In [2]:
df = pd.read_csv("E:\MCA\CSET 654 -Data Analysis\Lab\DataSET\Enroll_dataset.csv",
    encoding="latin1")

<>:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\goelk\AppData\Local\Temp\ipykernel_6240\471672260.py:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  df = pd.read_csv("E:\MCA\CSET 654 -Data Analysis\Lab\DataSET\Enroll_dataset.csv",

In [3]:
df.head()        # First 5 rows

,ï»¿S.no,Name,Course Id,CourseName,College Roll Number,Gender,City,Profession,Qualification,Degree,Department,Study Year,University Code,Timeline
0,1,singh saksham kumar raju,noc26-ge30,Entrepreneurship Essentials,E23CSEU2176,male,Goutam Budd Nagar,student,pre_university,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026
1,2,Aryama Swadha,noc26-ge30,Entrepreneurship Essentials,E23CSEU1530,female,Noida,student,bachelor4yr,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026
2,3,Paramdeep Singh,noc26-cs34,Blockchain and its Applications,E23CSEU2252,male,Kichha,student,pre_university,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026
3,4,Avantika Singh,noc26-cs64,Business Intelligence & Analytics,E23CSEU2103,female,Farrukhabad,student,pre_university,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026
4,5,PRANSHU SAXENA,noc26-cs57,Cryptography and Network Security,NaN,male,Dadri,faculty,doctoral,NaN,Computer Science and Engineering,NaN,890,Jan-Apr 2026

In [4]:
df.tail()        # Last 5 rows

,ï»¿S.no,Name,Course Id,CourseName,College Roll Number,Gender,City,Profession,Qualification,Degree,Department,Study Year,University Code,Timeline
3475,3476,Sahil Singh,noc26-cs10,Artificial Intelligence (AI) for Management,E23CSEU2027,male,Loni,student,pre_university,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026
3476,3477,Shourya Kakkar,noc26-cs64,Business Intelligence & Analytics,E23CSEU0289,male,East Delhi,student,bachelor4yr,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026
3477,3478,RIYA SINGH,noc26-ge30,Entrepreneurship Essentials,E23CSEU1650,female,Gautam Budh Nagar,student,bachelor4yr,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026
3478,3479,ABHISHEK KHAIWAL,noc26-cs64,Business Intelligence & Analytics,E23CSEU2041,male,Gautam_Buddha_Nagar,student,bachelor3yr,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026
3479,3480,Prateek Pant,noc26-cs88,Introduction to Large Language Models (LLMs),E23CSEU1130,male,Almora,student,bachelor4yr,btech,Computer Science and Engineering,3.0,890,Jan-Apr 2026

In [5]:
df.sample()  # Random rows

,ï»¿S.no,Name,Course Id,CourseName,College Roll Number,Gender,City,Profession,Qualification,Degree,Department,Study Year,University Code,Timeline
2754,2755,Ansh pandey,noc26-cs34,Blockchain and its Applications,S24CSEU1103,male,Haldwani,student,high_school,btech,Computer Science and Engineering,2.0,890,Jan-Apr 2026

In [6]:
df.dtypes()

TypeError: 'Series' object is not callable

In [ ]:
df.shape #(rows, columns)

(9994, 21)

In [ ]:
df.size  #Total values (rows × columns)

209874

In [ ]:
df.ndim  #Number of dimensions

2

In [ ]:
df.columns  # Column names

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df.index  # Index info

RangeIndex(start=0, stop=9994, step=1)

In [ ]:
df.info()  # Data types + non-null count

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
df.describe() # Statistical summary (numeric)

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [ ]:
df.describe(include='all')  # Full summary

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994,9994,9994,9994,9994,9994,9994,...,9994.000000,9994,9994,9994,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
unique,NaN,5009,1237,1334,4,793,793,3,1,531,...,NaN,4,1862,3,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,09-05-2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN,NaN,NaN
freq,NaN,14,38,35,5968,37,37,5191,9994,915,...,NaN,3203,19,6026,1523,48,NaN,NaN,NaN,NaN
mean,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55190.379428,NaN,NaN,NaN,NaN,NaN,229.858001,3.789574,0.156203,28.656896
std,2885.163629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32063.693350,NaN,NaN,NaN,NaN,NaN,623.245101,2.225110,0.206452,234.260108
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1040.000000,NaN,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23223.000000,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56430.500000,NaN,NaN,NaN,NaN,NaN,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90008.000000,NaN,NaN,NaN,NaN,NaN,209.940000,5.000000,0.200000,29.364000
max,9994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000

#### 2 Columns and Row Selection

#### 2. Data Cleaning & Missing Values

In [ ]:
df.isnull() # null value

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9990,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9993,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isna() # null value

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9990,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9993,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.notnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9990,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9991,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9992,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9993,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [ ]:
df.notna()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9990,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9991,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9992,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9993,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [ ]:
df.isnull().sum  # Missing count per column

<bound method DataFrame.sum of       Row ID  Order ID  Order Date  Ship Date  Ship Mode  Customer ID  \
0      False     False       False      False      False        False
1      False     False       False      False      False        False
2      False     False       False      False      False        False
3      False     False       False      False      False        False
4      False     False       False      False      False        False
...      ...       ...         ...        ...        ...          ...
9989   False     False       False      False      False        False
9990   False     False       False      False      False        False
9991   False     False       False      False      False        False
9992   False     False       False      False      False        False
9993   False     False       False      False      False        False

      Customer Name  Segment  Country   City  ...  Postal Code  Region  \
0             False    False    False  False  ...        False   False
1             False    False    False  False  ...        False   False
2             False    False    False  False  ...        False   False
3             False    False    False  False  ...        False   False
4             False    False    False  False  ...        False   False
...             ...      ...      ...    ...  ...          ...     ...
9989          False    False    False  False  ...        False   False
9990          False    False    False  False  ...        False   False
9991          False    False    False  False  ...        False   False
9992          False    False    False  False  ...        False   False
9993          False    False    False  False  ...        False   False

      Product ID  Category  Sub-Category  Product Name  Sales  Quantity  \
0          False     False         False         False  False     False
1          False     False         False         False  False     False
2          False     False         False         False  False     False
3          False     False         False         False  False     False
4          False     False         False         False  False     False
...          ...       ...           ...           ...    ...       ...
9989       False     False         False         False  False     False
9990       False     False         False         False  False     False
9991       False     False         False         False  False     False
9992       False     False         False         False  False     False
9993       False     False         False         False  False     False

      Discount  Profit
0        False   False
1        False   False
2        False   False
3        False   False
4        False   False
...        ...     ...
9989     False   False
9990     False   False
9991     False   False
9992     False   False
9993     False   False

[9994 rows x 21 columns]>

In [ ]:
df.dropna()  #drop rows with NaN

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,05-09-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
df.dropna(axis=1)  #drop columns with NaN

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,05-09-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
df.fillna(0)  # fill Na

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,05-09-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
df.fillna(method='ffill') #fill na

C:\Users\goelk\AppData\Local\Temp\ipykernel_20596\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,05-09-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
df.fillna(method='bfill') #fill na

C:\Users\goelk\AppData\Local\Temp\ipykernel_20596\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05-04-2017,05-09-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

#### 3. Aggregation and Statistics

In [7]:
df.mean() # mean value

TypeError: Cannot perform reduction 'mean' with string dtype

In [8]:
df.sum() # sum

ï»¿S.no                                                          6056940
Name                   singh saksham  kumar rajuAryama SwadhaParamdee...
Course Id              noc26-ge30noc26-ge30noc26-cs34noc26-cs64noc26-...
CourseName             Entrepreneurship EssentialsEntrepreneurship Es...
College Roll Number    E23CSEU2176E23CSEU1530E23CSEU2252E23CSEU2103E2...
Gender                 malefemalemalefemalemalemalemalemalemalemalema...
City                   Goutam Budd NagarNoidaKichhaFarrukhabadDadriMi...
Profession             studentstudentstudentstudentfacultystudentstud...
Qualification          pre_universitybachelor4yrpre_universitypre_uni...
Degree                 btechbtechbtechbtechbtechbtechbtechbtechbtechb...
Department             Computer Science and EngineeringComputer Scien...
Study Year                                                        9308.0
University Code                                                  3097200
Timeline               Jan-Apr 2026Jan-Apr 2026Jan-Apr 2026Jan-Apr 20...
dtype: object

In [9]:
df.min() # min value

ï»¿S.no                                              1
Name                                        8953017920
Course Id                                   noc26-ae01
CourseName             AI in Human Resource Management
College Roll Number                               0905
Gender                                          female
City                                         A. C Lane
Profession                                     faculty
Qualification                              bachelor3yr
Degree                                 arts_humanities
Department                      Accounting and Finance
Study Year                                        -1.0
University Code                                    890
Timeline                                  Jan-Apr 2026
dtype: object

In [10]:
df.max() # max

ï»¿S.no                                                             3480
Name                                                         yuvraj garg
Course Id                                                     noc26-ph10
CourseName             Yoga and Positive Psychology for Managing Care...
College Roll Number                         s24scsetp0008@bennett.edu.in
Gender                                                             other
City                                                            shahabad
Profession                                                       student
Qualification                                             pre_university
Degree                                                           science
Department                                                        Others
Study Year                                                           6.0
University Code                                                      890
Timeline                                                    Jan-Apr 2026
dtype: object

In [11]:
df.median() # median value

TypeError: Cannot perform reduction 'median' with string dtype

In [12]:
df.mode() # mode value

,ï»¿S.no,Name,Course Id,CourseName,College Roll Number,Gender,City,Profession,Qualification,Degree,Department,Study Year,University Code,Timeline
0,1,Navya juneja,noc26-ge30,Entrepreneurship Essentials,E23CSEU2149,male,Gautam Budh Nagar,student,pre_university,btech,Computer Science and Engineering,3.0,890.0,Jan-Apr 2026
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475,3476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3476,3477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3477,3478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3478,3479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3479,3480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.std() # standard value

TypeError: Cannot perform reduction 'std' with string dtype

In [14]:
df.var() # standar variences

TypeError: Cannot perform reduction 'var' with string dtype

In [15]:
df.count() # count value

ï»¿S.no                3480
Name                   3480
Course Id              3480
CourseName             3480
College Roll Number    3308
Gender                 3480
City                   3479
Profession             3480
Qualification          3480
Degree                 3308
Department             3477
Study Year             3338
University Code        3480
Timeline               3480
dtype: int64

In [16]:
df.nunique() # unique value

ï»¿S.no                3480
Name                   2312
Course Id               148
CourseName              148
College Roll Number    2306
Gender                    3
City                    429
Profession                2
Qualification             8
Degree                   10
Department               20
Study Year                7
University Code           1
Timeline                  1
dtype: int64

In [17]:
df.quantile(0.25)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [20]:
! pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in d:\python\Lib\site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in d:\python\Lib\site-packages (from seaborn) (3.0.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in d:\python\Lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in d:\python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in d:\python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in d:\python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\python\Lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in d:\python\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [22]:
pip install ydata profiling

Collecting ydata
  Downloading ydata-0.2.tar.gz (3.3 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting profiling
  Downloading profiling-0.1.3.tar.gz (36 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: requests in d:\python\Lib\site-packages (from ydata) (2.32.5)
Requirement already satisfied: python-dateutil in d:\python\Lib\site-packages (from ydata) (2.9.0.post0)
Collecting valuedispatch>=0.0.1 (from profiling)
  Downloading valuedispatch-0.0.1.tar.gz (1.8 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: click>=4.1 in d:\python\Lib\site-packages (from profiling) (8.3.1)
Collecting click-default-group>=1.2 (from profiling)
  Downloading click_default_group-1.2.4-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: six>=1.8.0 in d:\python\Lib\site-packages (from profiling) (1.17.0)
INFO: pip is looking at multiple versions of profiling to determine which version is compatible with other requirements. This could take a while.
Collecting profiling
  Downloading profiling-0.1.2.tar.gz (35 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Downloading profiling-0.1.1.tar.gz (36 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'

The conflict is caused by:
    profiling 0.1.3 depends on urwid>=1.2.1
    profiling 0.1.2 depends on urwid>=1.2.1
    profiling 0.1.1 depends on urwid>=1.2.1

Additionally, some packages in these conflicts have no matching distributions available for your environment:
    urwid

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

Note: you may need to restart the kernel to use updated packages.

ERROR: Cannot install profiling==0.1.1, profiling==0.1.2 and profiling==0.1.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

In [4]:
--version

NameError: name 'version' is not defined

In [5]:
pip install sweetviz

Collecting sweetviz
  Downloading sweetviz-2.3.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in d:\python\Lib\site-packages (from sweetviz) (3.0.0)
Requirement already satisfied: numpy>=1.16.0 in d:\python\Lib\site-packages (from sweetviz) (2.4.2)
Requirement already satisfied: matplotlib>=3.1.3 in d:\python\Lib\site-packages (from sweetviz) (3.10.8)
Collecting tqdm>=4.43.0 (from sweetviz)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: scipy>=1.3.2 in d:\python\Lib\site-packages (from sweetviz) (1.17.0)
Requirement already satisfied: jinja2>=2.11.1 in d:\python\Lib\site-packages (from sweetviz) (3.1.6)
Collecting importlib-resources>=1.2.0 (from sweetviz)
  Downloading importlib_resources-6.5.2-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: MarkupSafe>=2.0 in d:\python\Lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\python\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\python\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\python\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\python\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.1.3->sweetviz) (26.0)
Requirement already satisfied: pillow>=8 in d:\python\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.1.1)
Requirement already satisfied: pyparsing>=3 in d:\python\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\python\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\python\Lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.3)
Requirement already satisfied: six>=1.5 in d:\python\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in d:\python\Lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)
Downloading sweetviz-2.3.1-py3-none-any.whl (15.1 MB)
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   -- ------------------------------------- 0.8/15.1 MB 5.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.8/15.1 MB 5.0 MB/s eta 0:00:03
   ------ --------------------------------- 2.6/15.1 MB 4.7 MB/s eta 0:00:03
   --------- ------------------------------ 3.7/15.1 MB 4.7 MB/s eta 0:00:03
   ----------- ---------------------------- 4.5/15.1 MB 4.6 MB/s eta 0:00:03
   ------------- -------------------------- 5.2/15.1 MB 4.3 MB/s eta 0:00:03
   --------------- ------------------------ 6.0/15.1 MB 4.4 MB/s eta 0:00:03
   ------------------ --------------------- 7.1/15.1 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.1 MB 4.4 MB/s eta 0:00:02
   ----------------------- ---------------- 8.9/15.1 MB 4.4 MB/s eta 0:00:02
   -------------------------- ------------- 10.0/15.1 MB 4.4 MB/s eta 0:00:02
   ----------------------------- ---------- 11.0/15.1 MB 4.5 MB/s eta 0:00:01
   ----------------------------- ---------- 11.3/15.1 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 12.3/15.1 MB 4.3 MB/s eta 0:00:01
   ----------------------------------- ---- 13.4/15.1 MB 4.3 MB/s eta 0:00:01
   -------------------------------------- - 14.4/15.1 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  14.9/15.1 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 15.1/15.1 MB 4.2 MB/s  0:00:03
Downloading importlib_resources-6.5.2-py3-none-any.whl (37 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, importlib-resources, sweetviz

   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ------------- -------------------------- 1/3 [importlib-resources]
   ------------- -------------------------- 1/3 [importlib-resources]
   ------------- -------------------------- 1/3 [importlib-resources]
   ------------- -------------------------- 1/3 [importlib-resources]
   ------------- -------------------------- 1/3 [importlib-resources]
   ------------- -------------------------- 1/3 [importlib-resources]
   ------------- -------------------------- 1/3 [importlib-resources]
   -------------------------- ------------- 2/3 [sweetviz]
   -------------------------- ------------- 2/3 [sweetviz]
   -------------------------- ------------- 2/3 [sweetviz]
   -------------------------- ------------- 2/3 [sweetviz]
   -------------------------- ------------- 2/3 [sweetviz]
   -------------------------- ------------- 2/3 [sweetviz]
   -------------------------- ------------- 2/3 [sweetviz]
   ---------------------------------------- 3/3 [sweetviz]

Successfully installed importlib-resources-6.5.2 sweetviz-2.3.1 tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

In [27]:
pip install ydata-profiling

Note: you may need to restart the kernel to use updated packages.

ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python >=3.7,<3.11; 4.1.0 Requires-Python >=3.7,<3.12; 4.1.1 Requires-Python >=3.7,<3.12; 4.1.2 Requires-Python >=3.7,<3.12; 4.10.0 Requires-Python >=3.7,<3.13; 4.11.0 Requires-Python >=3.7,<3.13; 4.12.0 Requires-Python >=3.7,<3.13; 4.12.1 Requires-Python >=3.7,<3.13; 4.12.2 Requires-Python >=3.7,<3.13; 4.13.0 Requires-Python >=3.7,<3.13; 4.14.0 Requires-Python >=3.7,<3.13; 4.15.0 Requires-Python >=3.7,<3.13; 4.15.1 Requires-Python >=3.7,<3.13; 4.16.0 Requires-Python >=3.7,<3.13; 4.16.1 Requires-Python >=3.7,<3.13; 4.17.0 Requires-Python >=3.7,<3.14; 4.18.0 Requires-Python >=3.10,<3.14; 4.18.1 Requires-Python >=3.10,<3.14; 4.2.0 Requires-Python >=3.7,<3.12; 4.3.0 Requires-Python >=3.7,<3.12; 4.3.1 Requires-Python >=3.7,<3.12; 4.3.2 Requires-Python >=3.7,<3.12; 4.4.0 Requires-Python >=3.7,<3.12; 4.5.0 Requires-Python >=3.7,<3.12; 4.5.1 Requires-Python >=3.7,<3.12; 4.6.0 Requires-Python >=3.7,<3.12; 4.6.1 Requires-Python >=3.7,<3.12; 4.6.2 Requires-Python >=3.7,<3.12; 4.6.3 Requires-Python >=3.7,<3.12; 4.6.4 Requires-Python >=3.7,<3.12; 4.6.5 Requires-Python >=3.7,<3.12; 4.7.0 Requires-Python >=3.7,<3.13; 4.8.3 Requires-Python >=3.7,<3.13; 4.9.0 Requires-Python >=3.7,<3.13
ERROR: Could not find a version that satisfies the requirement ydata-profiling (from versions: none)
ERROR: No matching distribution found for ydata-profiling

In [7]:
pip install ipywidgets jupyter

Collecting ipywidgets
  Downloading ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: comm>=0.1.3 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipywidgets) (9.10.0)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipywidgets) (5.14.3)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Collecting notebook (from jupyter)
  Downloading notebook-7.5.5-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Downloading nbconvert-7.17.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: ipykernel in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from jupyter) (7.2.0)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.5.6-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: colorama>=0.4.4 in d:\python\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipykernel->jupyter) (1.8.20)
Requirement already satisfied: jupyter-client>=8.8.0 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipykernel->jupyter) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: nest-asyncio>=1.4 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging>=22 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipykernel->jupyter) (26.0)
Requirement already satisfied: psutil>=5.7 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from ipykernel->jupyter) (6.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\python\Lib\site-packages (from jupyter-client>=8.8.0->ipykernel->jupyter) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\goelk\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.5.1)
Requirement already satisfied: six>=1.5 in d:\python\Lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.8.0->ipykernel->jupyter) (1.17.0)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Downloading async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting httpx<1,>=0.25.0 (from jupyterlab->jupyter)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: jinja2>=3.0.3 in d:\python\Lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Downloading jupyter_lsp-2.3.0-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.4.0 (from jupyterlab->jupyter)
  Downloading jupyter_server-2.17.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Downloading notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting setuptools>=41.1.0 (from jupyterlab->jupyter)
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: anyio in d:\python\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.12.1)
Requirement already satisfied: certifi in d:\python\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.2.25)
Collecting httpcore==1.* (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in d:\python\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.11)
Requirement already satisfied: h11>=0.16 in d:\python\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jupyter_events-0.12.0-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading prometheus_client-0.24.1-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty>=2.0.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pywinpty-3.0.3-cp314-cp314-win_amd64.whl.metadata (5.9 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading json5-0.13.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: requests>=2.31 in d:\python\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.32.5)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Requirement already satisfied: MarkupSafe>=2.0 in d:\python\Lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in d:\python\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (25.4.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading rpds_py-0.30.0-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading python_json_logger-4.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting pyyaml>=5.3 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jsonpointer-3.1.0-py3-none-any.whl.metadata (2.4 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Downloading mistune-3.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Downloading nbclient-0.10.4-py3-none-any.whl.metadata (8.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\python\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\python\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.6.3)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting cffi>=2.0.0b1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading cffi-2.0.0-cp314-cp314-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0b1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert->jupyter)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\python\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (4.15.0)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: tzdata in d:\python\Lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2025.3)
Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
   ---------------------------------------- 0.0/914.9 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/914.9 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/914.9 kB ? eta -:--:--
   --------------------- ---------------- 524.3/914.9 kB 723.0 kB/s eta 0:00:01
   -------------------------------- ----- 786.4/914.9 kB 832.4 kB/s eta 0:00:01
   ---------------------------------------- 914.9/914.9 kB 747.6 kB/s  0:00:01
Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 1.1 MB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.2 MB 1.2 MB/s eta 0:00:02
   ----------------------- ---------------- 1.3/2.2 MB 1.3 MB/s eta 0:00:01
   ---------------------------- ----------- 1.6/2.2 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 1.5 MB/s  0:00:01
Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Downloading jupyterlab-4.5.6-py3-none-any.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.4 MB 2.1 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.4 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.4 MB 1.9 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/12.4 MB 1.3 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/12.4 MB 1.3 MB/s eta 0:00:09
   ----- ---------------------------------- 1.8/12.4 MB 1.2 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.4 MB 1.2 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.4 MB 1.2 MB/s eta 0:00:09
   -------- ------------------------------- 2.6/12.4 MB 1.2 MB/s eta 0:00:09
   --------- ------------------------------ 2.9/12.4 MB 1.3 MB/s eta 0:00:08
   ---------- ----------------------------- 3.4/12.4 MB 1.3 MB/s eta 0:00:07
   ------------ --------------------------- 3.9/12.4 MB 1.4 MB/s eta 0:00:07
   ------------- -------------------------- 4.2/12.4 MB 1.4 MB/s eta 0:00:06
   --------------- ------------------------ 4.7/12.4 MB 1.5 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/12.4 MB 1.6 MB/s eta 0:00:05
   ----------------- ---------------------- 5.5/12.4 MB 1.6 MB/s eta 0:00:05
   ------------------- -------------------- 6.0/12.4 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 6.8/12.4 MB 1.7 MB/s eta 0:00:04
   ---------------------- ----------------- 7.1/12.4 MB 1.7 MB/s eta 0:00:04
   ------------------------ --------------- 7.6/12.4 MB 1.7 MB/s eta 0:00:03
   -------------------------- ------------- 8.1/12.4 MB 1.8 MB/s eta 0:00:03
   --------------------------- ------------ 8.7/12.4 MB 1.8 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.4 MB 1.8 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.4 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.4 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.4 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 1.7 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 1.7 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 1.7 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.6 MB/s eta 0:00:02

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (0 bytes/14.6 MB, attempt 1)
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (262 kB/14.6 MB, attempt 2)
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (524 kB/14.6 MB, attempt 3)
ERROR: Exception:
Traceback (most recent call last):
  File "d:\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "d:\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ~~~~~~~~~~~~~^^^^^
  File "d:\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ~~~~~~~~~~~~~^^^^^
  File "d:\python\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 100, in read
    data: bytes = self.__fp.read(amt)
                  ~~~~~~~~~~~~~~^^^^^
  File "d:\python\Lib\http\client.py", line 484, in read
    s = self.fp.read(amt)
  File "d:\python\Lib\socket.py", line 725, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "d:\python\Lib\ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "d:\python\Lib\ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python\Lib\site-packages\pip\_internal\cli\base_command.py", line 107, in _run_wrapper
    status = _inner_run()
  File "d:\python\Lib\site-packages\pip\_internal\cli\base_command.py", line 98, in _inner_run
    return self.run(options, args)
           ~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\python\Lib\site-packages\pip\_internal\cli\req_command.py", line 96, in wrapper
    return func(self, options, args)
  File "d:\python\Lib\site-packages\pip\_internal\commands\install.py", line 419, in run
    preparer.prepare_linked_requirements_more(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        requirement_set.requirements.values()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\python\Lib\site-packages\pip\_internal\operations\prepare.py", line 569, in prepare_linked_requirements_more
    self._complete_partial_requirements(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partially_downloaded_reqs,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
        parallel_builds=parallel_builds,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\python\Lib\site-packages\pip\_internal\operations\prepare.py", line 478, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
                               ^^^^^^^^^^^^^^
  File "d:\python\Lib\site-packages\pip\_internal\network\download.py", line 183, in batch
    filepath, content_type = self(link, location)
                             ~~~~^^^^^^^^^^^^^^^^
  File "d:\python\Lib\site-packages\pip\_internal\network\download.py", line 196, in __call__
    self._attempt_resumes_or_redownloads(download, resp)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "d:\python\Lib\site-packages\pip\_internal\network\download.py", line 246, in _attempt_resumes_or_redownloads
    self._process_response(download, resume_resp)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python\Lib\site-packages\pip\_internal\network\download.py", line 211, in _process_response
    for chunk in chunks:
                 ^^^^^^
  File "d:\python\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 69, in _rich_download_progress_bar
    for chunk in iterable:
                 ^^^^^^^^
  File "d:\python\Lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
                 ~~~~~~~~~~~~~~~~~~~^
        chunk_size,
        ^^^^^^^^^^^
    ...<22 lines>...
        decode_content=False,
        ^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "d:\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "d:\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
         ~~~~~~~~~~~~~~~~~~~^^
  File "d:\python\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "d:\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [8]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import sweetviz as sv

df = pd.read_csv(
    r"E:\MCA\CSET 654 -Data Analysis\Lab\DataSET\Enroll_dataset.csv",
    encoding="latin1"
)

report = sv.analyze(df)
report.show_html("output.html")

ModuleNotFoundError: No module named 'pkg_resources'

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Import profiling library
from ydata_profiling import ProfileReport

# Load dataset (your path)
df = pd.read_csv(
    r"E:\MCA\CSET 654 -Data Analysis\Lab\DataSET\Enroll_dataset.csv",
    encoding="latin1"
)

# Show first few rows (optional check)
print(df.head())

# Generate profile report
profile = ProfileReport(df, title="Dataset Profiling Report", explorative=True)

# Save report as HTML file
profile.to_file("output.html")

print("Report generated successfully! Open output.html")

ModuleNotFoundError: No module named 'ydata_profiling'